import { AppShell } from "@/components/layout/app-shell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { requireUser } from "@/lib/auth/guards";
import { mockInventory } from "@/lib/data/mock";

export default async function InventoryPage() {
  const user = await requireUser();

  return (
    <AppShell user={user} title="Inventory">
      <div className="space-y-4">
        <Card>
          <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
            <div>
              <p className="text-xs uppercase tracking-[0.22em] text-[var(--muted)]">Daily counts and variance</p>
              <h2 className="section-title mt-2 text-3xl">Bar count session</h2>
              <p className="mt-2 text-sm text-[var(--muted)]">
                Variance is generated by Postgres and reorder alerts fire when actual quantity falls to 25% of par.
              </p>
            </div>
            <Button>Scan shelf photo</Button>
          </div>
        </Card>

        <Card>
          <div className="overflow-x-auto">
            <table className="min-w-full text-left text-sm">
              <thead className="text-xs uppercase tracking-[0.2em] text-[var(--muted)]">
                <tr>
                  <th className="pb-3">Item</th>
                  <th className="pb-3">Type</th>
                  <th className="pb-3">Par</th>
                  <th className="pb-3">Expected</th>
                  <th className="pb-3">Actual</th>
                  <th className="pb-3">Variance</th>
                  <th className="pb-3">Distributor</th>
                </tr>
              </thead>
              <tbody>
                {mockInventory.map((item) => (
                  <tr key={item.itemId} className={item.flagged ? "flag-row" : undefined}>
                    <td className="py-3">
                      <div className="font-medium">{item.brand}</div>
                      <div className="text-xs text-[var(--muted)]">{item.size}</div>
                    </td>
                    <td className="py-3 uppercase">{item.spiritType}</td>
                    <td className="py-3 font-mono">{item.par}</td>
                    <td className="py-3 font-mono">{item.expectedQuantity}</td>
                    <td className="py-3 font-mono">{item.actualQuantity}</td>
                    <td className="py-3">
                      <Badge tone={item.variance > 0 ? "alert" : "success"}>{item.variance}</Badge>
                    </td>
                    <td className="py-3">{item.distributor}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Card>
      </div>
    </AppShell>
  );
}
